services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: automate
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20

#  postgres:
#    image: postgres:16
#    container_name: postgres-db
#    environment:
#      POSTGRES_DB: automate
#      POSTGRES_USER: appuser
#      POSTGRES_PASSWORD: apppass
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U appuser -d automate" ]
#      interval: 5s
#      timeout: 5s
#      retries: 20

  app:
    image: automate
    container_name: automate-app
    depends_on:
#      - postgres
      - mysql
    ports:
      - "8088:8080"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/automate
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/automate?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass

volumes:
  mysql-data:
#   postgres-data: